# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "centos/7"

  config.vm.define "controller" do |node|
    node.vm.hostname = "controller"
    for p in [:virtualbox, :libvirt] do
      node.vm.provider p do |provider|
        provider.memory = 4096
      end
    end
    node.vm.network "private_network", ip: "192.168.10.10"
    node.vm.provision "shell", path: "provision/openstack_base.sh"
  end

  config.vm.define "network" do |node|
    node.vm.hostname = "network"
    for p in [:virtualbox, :libvirt] do
      node.vm.provider p do |provider|
        provider.memory = 2048
      end
    end
    node.vm.network "private_network", ip: "192.168.33.11"
    node.vm.provision "shell", path: "provision/openstack_base.sh"
  end

  config.vm.define "ceph1" do |node|
    node.vm.hostname = "ceph1"
    for p in [:virtualbox, :libvirt] do
      node.vm.provider p do |provider|
        provider.memory = 4096
      end
    end
    node.vm.network "private_network", ip: "192.168.33.21"
  end

  config.vm.define "ceph2" do |node|
    node.vm.hostname = "ceph2"
    for p in [:virtualbox, :libvirt] do
      node.vm.provider p do |provider|
        provider.memory = 2048
      end
    end
    node.vm.network "private_network", ip: "192.168.33.22"
  end

  config.vm.define "ceph3" do |node|
    node.vm.hostname = "ceph3"
    for p in [:virtualbox, :libvirt] do
      node.vm.provider p do |provider|
        provider.memory = 4096
      end
    end
    node.vm.network "private_network", ip: "192.168.33.23"
  end

end
